<?php

{
    "taxDateView": "18 Nov 2024",
    "printUserName": "sprsales.hjg@gmail.com",
    "reverseInvoice": false,
    "numericField10": 0,
    "expiredDate": "-",
    "reverseInvoiceStatus": null,
    "masterProjectId": null,
    "receiveItem": false,
    "lastReturnDate": null,
    "currencyId": 50,
    "efakturProceed": false,
    "transDateView": "18 Nov 2024",
    "branchId": 50,
    "tax1Id": 50,
    "lastPaymentId": null,
    "billOfMaterial": false,
    "taxNumber": null,
    "retailWpName": "AUTOPARTS MOTOR TOKO",
    "tax1Amount": 416761,
    "salesOrder": false,
    "commentCount": 0,
    "hasNPWP": false,
    "orderDownPayment": null,
    "taxableAmount2": 0,
    "taxableAmount1": 3788743.338739,
    "lastCashDiscPercent": "",
    "taxableAmount4": 0,
    "poNumber": null,
    "charField10": "",
    "processStages": false,
    "posCreateDate": null,
    "preliminarySurvey": false,
    "journalId": 437467,
    "availableDownPayment": 0,
    "taxReturn": 0,
    "exchangeInvoiceId": null,
    "customerClaim": false,
    "journal": false,
    "deliveryPacking": false,
    "paymentWithEPayment": false,
    "customerId": 62,
    "deliveryPackingId": null,
    "currency": {
      "symbol": "Rp",
      "defaultArAccountId": 57,
      "code": "IDR",
      "defaultSalesDiscAccountId": 60,
      "optLock": 7,
      "currencyConverterType": "TO_LOCAL",
      "defaultAdvSalesAccountId": 59,
      "defaultAdvPurchaseAccountId": 58,
      "defaultRealizeGlAccountId": 61,
      "name": "Indonesian Rupiah",
      "codeSymbol": "IDR Rp",
      "id": 50,
      "defaultApAccountId": 56,
      "defaultUnrealizeGlAccountId": 62
    },
    "vendorPrice": false,
    "paymentTermId": 56,
    "outstanding": true,
    "fobId": null,
    "deliveryOrder": false,
    "efakturPdfFilePath": "",
    "taxReceipt": 0,
    "taxReported": false,
    "deliveryPackingNumber": "",
    "taxable1Total": 3788743.338739,
    "detailDownPayment": [],
    "onlineOrder": false,
    "dueDate": "17/01/2025",
    "inclusiveTax": true,
    "taxableDiscount4": 0,
    "taxableDiscount2": 0,
    "hasVaCompanyCode": false,
    "toAddress": "JL. RAYA TELUKAN 9A SOLO BACEM\nSOLO",
    "taxableDiscount1": 0,
    "rollOver": false,
    "masterDepartmentId": 54,
    "taxOwing": 0,
    "epaymentStatus": null,
    "retailIdCard": "",
    "itemAdjustment": false,
    "taxReceiptHistory": [],
    "masterPosSalesType": null,
    "periodEnd": false,
    "workOrder": false,
    "masterSalesmanId": 150,
    "shipment": null,
    "invoiceTimeView": "01 Jan 1970",
    "cashierEmployeeId": null,
    "epaymentCode": null,
    "sptMasaId": null,
    "primeReturn": 0,
    "salesQuotation": false,
    "fixedAssetEdited": false,
    "fob": null,
    "taxDownPayment": 0,
    "tax1AmountBase": 416761,
    "canSelfPaidPph": false,
    "notesIdTax": null,
    "description": "VIA BARAKA (BAYAR TUJUAN)",
    "invoiceDp": false,
    "invoicePrintedTime": "18/11/2024, 13:02",
    "budgetPlan": false,
    "rate": 1,
    "efakturEmailTime": null,
    "lastPaymentDate": null,
    "transDate": "18/11/2024",
    "inputDownPayment": 0,
    "cashDiscount": 0,
    "primeReceipt": 0,
    "primeDownPayment": 0,
    "salesReceipt": false,
    "approvalStatus": "APPROVED",
    "tax2Id": null,
    "materialSlip": false,
    "sellingPriceAdjustment": false,
    "externalId": null,
    "cashierEmployeeName": "",
    "downPaymentAccountId": null,
    "taxDownPayment2": 0,
    "suggestedDiscount": 0,
    "taxDownPayment1": 0,
    "numericField9": 0,
    "numericField8": 0,
    "numericField7": 0,
    "createdBy": 125278,
    "shipmentId": null,
    "numericField6": 0,
    "numericField5": 0,
    "numericField4": 0,
    "purchaseOrder": false,
    "numericField3": 0,
    "salesAmountBase": 3788744.106,
    "numericField2": 0,
    "numericField1": 0,
    "userPrinted": 125278,
    "age": 1,
    "charField8": "",
    "charField9": "",
    "invoiceTime": "11:15:01",
    "tax4Amount": 0,
    "charField6": "",
    "tax1Rate": 11,
    "charField7": "",
    "charField4": "",
    "charField5": "",
    "optLock": 23,
    "epaymentSettingId": null,
    "printedTimeView": "18 Nov 2024 13:02:48",
    "epaymentAmount": 0,
    "percentTaxable": 100,
    "reversePercentShipped": 0,
    "arAccountId": 115,
    "vaNumber": "",
    "returnHistory": [],
    "number": "2411-0900DA",
    "printedTime": "18/11/2024, 13:02",
    "taxable2Total": 0,
    "charField2": "",
    "charField3": "",
    "dueDateView": "17 Jan 2025",
    "charField1": "",
    "id": 202953,
    "taxType": "BKN_PEMUNGUT_PPN",
    "hasStatusHistory": true,
    "dateField2": null,
    "dateField1": null,
    "taxable": true,
    "customerHasDownPayment": false,
    "salesInvoice": true,
    "purchaseInvoice": false,
    "shipDate": "18/11/2024",
    "hasExchangeInvoice": false,
    "uniqueAmount": 0,
    "transferOrder": false,
    "detailExpense": [],
    "detailItem": [
      {
        "deliveryOrderDetailId": 541163,
        "hasPosSalesType": false,
        "lastItemDiscPercent": "54+5",
        "charField8": null,
        "returnQuantity": 0,
        "detailDynamicGroupTotalPrice": 0,
        "charField9": null,
        "processQuantityDesc": "",
        "charField6": null,
        "tax1Rate": 11,
        "charField7": null,
        "numericField10": 0,
        "charField4": null,
        "departmentId": 54,
        "charField5": null,
        "optLock": 74,
        "itemUnit": {
          "optLock": 0,
          "name": "SET",
          "id": 100
        },
        "detailSerialNumber": [],
        "salesOrderPoNumber": "",
        "waitressEmployeeId": null,
        "deliveryOrderDetail": {
          "id": 541163
        },
        "charField2": null,
        "charField3": null,
        "salesOrderDetailId": 834983,
        "reverseInvoiceUnitCost": 0,
        "charField1": "41201-80661O",
        "id": 492807,
        "salesman3Id": null,
        "dataClassification6Id": null,
        "salesQuotationDetailId": null,
        "unitPrice": 8210538,
        "useTax1": true,
        "dateField2": null,
        "dataClassification1": null,
        "salesmanName": "DIST-YUFA",
        "branchId": 50,
        "useTax3": false,
        "dataClassification3": null,
        "item": {
          "unit2Id": null,
          "charField8": null,
          "charField9": null,
          "charField6": null,
          "charField7": null,
          "numericField10": 0,
          "unit4Price": 0,
          "charField4": null,
          "charField5": null,
          "optLock": 26,
          "percentTaxable": 100,
          "itemBrandId": null,
          "ratioVendorUnit": 1,
          "unit3Price": 0,
          "salesDiscountGlAccountId": 211,
          "itemProduced": true,
          "charField2": null,
          "charField3": null,
          "charField1": "SLOW MOVING",
          "id": 620,
          "maxOptionModifier": null,
          "unitPrice": 0,
          "dateField2": null,
          "branchId": null,
          "tax1Id": 50,
          "dateField1": null,
          "useWholesalePrice": false,
          "onSales": 0,
          "unit5Price": 0,
          "unit2Price": 0,
          "suspended": false,
          "goodTransitGlAccountId": 126,
          "cogsGlAccountId": 214,
          "referenceSubstitutionId": null,
          "shortName": "GAR SET HI. DTRO XT 6X41 (2013",
          "itemSubstitutionId": null,
          "charField10": null,
          "unBilledGlAccountId": 197,
          "canChangeDetailGroup": false,
          "variantLabel2": null,
          "unit3Id": null,
          "dimWidth": 0,
          "variantLabel1": null,
          "salesRetGlAccountId": 208,
          "dimDepth": 0,
          "minimumQuantityReorder": 4,
          "lockTime": null,
          "vendorPrice": 0,
          "minimumQuantity": 0,
          "tax4Id": null,
          "dimHeight": 0,
          "additionalCost": false,
          "unit4Id": null,
          "notes": "DP-GRS01-41201-80661O",
          "purchaseRetGlAccountId": 123,
          "unit1": {
            "optLock": 0,
            "name": "SET",
            "id": 100
          },
          "variantParentId": null,
          "unit2": null,
          "unit3": null,
          "vendorUnit": {
            "optLock": 0,
            "name": "SET",
            "id": 100
          },
          "preferedVendorId": null,
          "ratio2": 0,
          "unit4": null,
          "unit5": null,
          "ratio4": 0,
          "ratio3": 0,
          "ratio5": 0,
          "variantDetail2": null,
          "tax3Id": null,
          "inventoryGlAccountId": 123,
          "variantDetail1": null,
          "controlQuantity": false,
          "weight": null,
          "upcNo": "41201-80661O",
          "substituted": false,
          "minOptionModifier": 1,
          "salesGlAccountId": 205,
          "name": "GEAR SET HI. DUTRO XT 6X41 (2013) OKY",
          "deliveryLeadTime": 0,
          "manageExpired": false,
          "no": "DP-GRS01-41201-80661O",
          "itemType": "INVENTORY",
          "defaultDiscount": null,
          "unit1Id": 100,
          "unit5Id": null,
          "itemCategoryId": 101,
          "hasImage": false,
          "tax1": {
            "pphPs4Type": null,
            "purchaseTaxGlAccountId": 82,
            "rate": 11,
            "pph23Type": null,
            "optLock": 3,
            "salesTaxGlAccountId": 81,
            "description": "Pajak Pertambahan Nilai",
            "pph15Type": null,
            "id": 50,
            "taxCode": "PPN",
            "taxType": "PPN",
            "taxInfo": "PPN 11%"
          },
          "tax2": null,
          "manageSN": false,
          "materialProduced": true,
          "variantSeq": null,
          "tax3": null,
          "tax4": null,
          "serialNumberType": null,
          "tax2Id": null,
          "cost": 0,
          "printDetailGroup": false,
          "calculateGroupPrice": false,
          "numericField9": 0,
          "defStandardCost": 0,
          "numericField8": 0,
          "numericField7": 0,
          "numericField6": 0,
          "numericField5": 0,
          "numericField4": 0,
          "numericField3": null,
          "numericField2": null,
          "numericField1": null,
          "vendorUnitId": 100,
          "unit1Price": 0
        },
        "purchaseInvoiceDetailId": null,
        "dataClassification1Id": null,
        "useTax2": false,
        "dateField1": null,
        "dataClassification2": null,
        "dataClassification5": null,
        "dataClassification4": null,
        "dataClassification7": null,
        "dataClassification6": null,
        "dataClassification9": null,
        "dataClassification8": null,
        "posSalesType": null,
        "tax1Amount": 355568.073568,
        "detailNotes": null,
        "warehouse": {
          "defaultWarehouse": true,
          "scrapWarehouse": false,
          "locationId": 52,
          "optLock": 3,
          "name": "HJA 1",
          "description": null,
          "pic": null,
          "id": 50,
          "suspended": false
        },
        "salesOrder": {
          "number": "SO24-11-1033-D",
          "id": 252259
        },
        "itemId": 620,
        "warehouseId": 50,
        "charField15": null,
        "charField13": null,
        "charField14": null,
        "charField11": null,
        "charField12": null,
        "useTax4": false,
        "charField10": null,
        "canChangeDetailGroup": false,
        "dataClassification10": null,
        "detailDynamicGroupPrice": 0,
        "detailName": "GEAR SET HI. DUTRO XT 6X41 (2013) OKY",
        "lastItemCashDiscount": 4622532.894,
        "totalPrice": 3588005.106,
        "salesInvoiceId": 202953,
        "groupSeq": null,
        "salesAmount": 3232437.799694,
        "purchaseInvoiceId": null,
        "dataClassification7Id": null,
        "seq": 1,
        "dataClassification2Id": null,
        "salesman2Id": null,
        "searchCharField1": {
          "id": "41201-80661O",
          "name": "41201-80661O"
        },
        "deliveryOrder": {
          "number": "DO2024-30935HJA",
          "id": 245204
        },
        "salesOrderDetail": {
          "id": 834983
        },
        "salesOrderId": 252259,
        "project": null,
        "deliveredQuantity": 0,
        "quantityDefault": 1,
        "itemDiscPercent": "54+5",
        "dataClassification8Id": null,
        "salesQuotationId": null,
        "salesman5Id": null,
        "deliveryOrderId": 245204,
        "dataClassification3Id": null,
        "salesman1Id": 150,
        "tax3Id": null,
        "controlQuantity": 0,
        "grossAmount": 7396881.081081,
        "projectId": null,
        "dppAmount": 3232437.032432,
        "tax2Amount": 0,
        "dynamicGroup": false,
        "posSalesTypeId": null,
        "dataClassification10Id": null,
        "itemCashDiscount": 4622532.894,
        "dataClassification9Id": null,
        "salesmanList": [
          {
            "resignMonth": null,
            "departmentId": null,
            "optLock": 1,
            "joinDateView": "27 Dec 2019",
            "resignYear": null,
            "contactInfoId": 150,
            "bankName": null,
            "startMonthPayment": 12,
            "nikNo": null,
            "addressId": 200,
            "number": "E.00003",
            "joinDate": "27/12/2019",
            "salesmanUserId": null,
            "nettoIncomeBefore": 0,
            "id": 150,
            "pphBefore": 0,
            "posRoleId": null,
            "startYearPayment": 2019,
            "employeeTaxStatus": "TK0",
            "bankAccount": null,
            "bankAccountName": null,
            "domisiliType": "INA",
            "branchId": 50,
            "bankCode": null,
            "calculatePtkp": true,
            "pph": true,
            "npwpNo": null,
            "suspended": false,
            "employeeWorkStatus": "PEGAWAI_TETAP",
            "name": "DIST-YUFA",
            "salesman": true,
            "resign": false
          }
        ],
        "department": {
          "sub": true,
          "parent": {
            "sub": true,
            "parent": {
              "sub": false,
              "parent": {
                "sub": false,
                "parent": null,
                "lvl": 0,
                "nameWithIndentStrip": "Root",
                "optLock": 0,
                "name": "Root",
                "description": null,
                "parentNode": true,
                "nameWithIndent": "Root",
                "id": 50,
                "suspended": false
              },
              "lvl": 1,
              "nameWithIndentStrip": "DEPT. SPAREPART",
              "optLock": 0,
              "name": "DEPT. SPAREPART",
              "description": null,
              "parentNode": true,
              "nameWithIndent": "DEPT. SPAREPART",
              "id": 51,
              "suspended": false
            },
            "lvl": 2,
            "nameWithIndentStrip": "- DISTRIBUTOR.",
            "optLock": 0,
            "name": "DISTRIBUTOR.",
            "description": null,
            "parentNode": true,
            "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR.",
            "id": 53,
            "suspended": false
          },
          "lvl": 3,
          "nameWithIndentStrip": "- - DISTRIBUTOR",
          "optLock": 0,
          "name": "DISTRIBUTOR",
          "description": null,
          "parentNode": false,
          "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR",
          "id": 54,
          "suspended": false
        },
        "salesman4Id": null,
        "tax3": null,
        "detailTaxName": "PPN 11%",
        "dataClassification5Id": null,
        "dataClassification4Id": null,
        "quantity": 1,
        "detailDynamicGroup": false,
        "totalCaptionSerialNumber": "0 No Seri/Produksi. Isikan 1 lagi",
        "numericField9": 0,
        "numericField8": 0,
        "numericField7": 0,
        "numericField6": 0,
        "numericField5": 0,
        "deliveryOrderPoNumber": "",
        "numericField4": 0,
        "itemUnitId": 100,
        "numericField3": 0,
        "salesAmountBase": 3232437.799694,
        "numericField2": 0,
        "itemHistoryId": null,
        "numericField1": 0,
        "unitRatio": 1
      },
      {
        "deliveryOrderDetailId": 541164,
        "hasPosSalesType": false,
        "lastItemDiscPercent": "",
        "charField8": null,
        "returnQuantity": 0,
        "detailDynamicGroupTotalPrice": 0,
        "charField9": null,
        "processQuantityDesc": "",
        "charField6": null,
        "tax1Rate": 11,
        "charField7": null,
        "numericField10": 0,
        "charField4": null,
        "departmentId": 54,
        "charField5": null,
        "optLock": 74,
        "itemUnit": {
          "optLock": 0,
          "name": "PCS",
          "id": 50
        },
        "detailSerialNumber": [],
        "salesOrderPoNumber": "",
        "waitressEmployeeId": null,
        "deliveryOrderDetail": {
          "id": 541164
        },
        "charField2": null,
        "charField3": null,
        "salesOrderDetailId": 834984,
        "reverseInvoiceUnitCost": 0,
        "charField1": "MD050103-I",
        "id": 492808,
        "salesman3Id": null,
        "dataClassification6Id": null,
        "salesQuotationDetailId": null,
        "unitPrice": 200500,
        "useTax1": true,
        "dateField2": null,
        "dataClassification1": null,
        "salesmanName": "DIST-YUFA",
        "branchId": 50,
        "useTax3": false,
        "dataClassification3": null,
        "item": {
          "unit2Id": null,
          "charField8": null,
          "charField9": null,
          "charField6": null,
          "charField7": null,
          "numericField10": 0,
          "unit4Price": 0,
          "charField4": null,
          "charField5": null,
          "optLock": 6,
          "percentTaxable": 100,
          "itemBrandId": null,
          "ratioVendorUnit": 1,
          "unit3Price": 0,
          "salesDiscountGlAccountId": 211,
          "itemProduced": false,
          "charField2": null,
          "charField3": null,
          "charField1": "SLOW MOVING",
          "id": 54700,
          "maxOptionModifier": 1,
          "unitPrice": 0,
          "dateField2": null,
          "branchId": null,
          "tax1Id": 50,
          "dateField1": null,
          "useWholesalePrice": false,
          "onSales": 0,
          "unit5Price": 0,
          "unit2Price": 0,
          "suspended": false,
          "goodTransitGlAccountId": 126,
          "cogsGlAccountId": 214,
          "referenceSubstitutionId": null,
          "shortName": "AS TEMPLAR MI. L300 DIESEL UTM",
          "itemSubstitutionId": null,
          "charField10": null,
          "unBilledGlAccountId": 197,
          "canChangeDetailGroup": false,
          "variantLabel2": null,
          "unit3Id": null,
          "dimWidth": 0,
          "variantLabel1": null,
          "salesRetGlAccountId": 208,
          "dimDepth": 0,
          "minimumQuantityReorder": 2,
          "lockTime": null,
          "vendorPrice": 0,
          "minimumQuantity": 0,
          "tax4Id": null,
          "dimHeight": 0,
          "additionalCost": false,
          "unit4Id": null,
          "notes": null,
          "purchaseRetGlAccountId": 123,
          "unit1": {
            "optLock": 0,
            "name": "PCS",
            "id": 50
          },
          "variantParentId": null,
          "unit2": null,
          "unit3": null,
          "vendorUnit": {
            "optLock": 0,
            "name": "PCS",
            "id": 50
          },
          "preferedVendorId": null,
          "ratio2": 0,
          "unit4": null,
          "unit5": null,
          "ratio4": 0,
          "ratio3": 0,
          "ratio5": 0,
          "variantDetail2": null,
          "tax3Id": null,
          "inventoryGlAccountId": 123,
          "variantDetail1": null,
          "controlQuantity": false,
          "weight": 0,
          "upcNo": null,
          "substituted": false,
          "minOptionModifier": 0,
          "salesGlAccountId": 205,
          "name": "AS TEMPLAR MI. L300 DIESEL UTM",
          "deliveryLeadTime": 0,
          "manageExpired": false,
          "no": "AP-ATM01-MD050103-I",
          "itemType": "INVENTORY",
          "defaultDiscount": null,
          "unit1Id": 50,
          "unit5Id": null,
          "itemCategoryId": 103,
          "hasImage": false,
          "tax1": {
            "pphPs4Type": null,
            "purchaseTaxGlAccountId": 82,
            "rate": 11,
            "pph23Type": null,
            "optLock": 3,
            "salesTaxGlAccountId": 81,
            "description": "Pajak Pertambahan Nilai",
            "pph15Type": null,
            "id": 50,
            "taxCode": "PPN",
            "taxType": "PPN",
            "taxInfo": "PPN 11%"
          },
          "tax2": null,
          "manageSN": false,
          "materialProduced": true,
          "variantSeq": null,
          "tax3": null,
          "tax4": null,
          "serialNumberType": "UNIQUE",
          "tax2Id": null,
          "cost": 0,
          "printDetailGroup": false,
          "calculateGroupPrice": false,
          "numericField9": 0,
          "defStandardCost": 0,
          "numericField8": 0,
          "numericField7": 0,
          "numericField6": 0,
          "numericField5": 0,
          "numericField4": 0,
          "numericField3": 0,
          "numericField2": 0,
          "numericField1": 0,
          "vendorUnitId": 50,
          "unit1Price": 0
        },
        "purchaseInvoiceDetailId": null,
        "dataClassification1Id": null,
        "useTax2": false,
        "dateField1": null,
        "dataClassification2": null,
        "dataClassification5": null,
        "dataClassification4": null,
        "dataClassification7": null,
        "dataClassification6": null,
        "dataClassification9": null,
        "dataClassification8": null,
        "posSalesType": null,
        "tax1Amount": 19869.369369,
        "detailNotes": null,
        "warehouse": {
          "defaultWarehouse": true,
          "scrapWarehouse": false,
          "locationId": 52,
          "optLock": 3,
          "name": "HJA 1",
          "description": null,
          "pic": null,
          "id": 50,
          "suspended": false
        },
        "salesOrder": {
          "number": "SO24-11-1033-D",
          "id": 252259
        },
        "itemId": 54700,
        "warehouseId": 50,
        "charField15": null,
        "charField13": null,
        "charField14": null,
        "charField11": null,
        "charField12": null,
        "useTax4": false,
        "charField10": null,
        "canChangeDetailGroup": false,
        "dataClassification10": null,
        "detailDynamicGroupPrice": 0,
        "detailName": "AS TEMPLAR MI. L300 DIESEL UTM",
        "lastItemCashDiscount": 0,
        "totalPrice": 200500,
        "salesInvoiceId": 202953,
        "groupSeq": null,
        "salesAmount": 180630.630631,
        "purchaseInvoiceId": null,
        "dataClassification7Id": null,
        "seq": 2,
        "dataClassification2Id": null,
        "salesman2Id": null,
        "searchCharField1": {
          "id": "MD050103-I",
          "name": "MD050103-I"
        },
        "deliveryOrder": {
          "number": "DO2024-30935HJA",
          "id": 245204
        },
        "salesOrderDetail": {
          "id": 834984
        },
        "salesOrderId": 252259,
        "project": null,
        "deliveredQuantity": 0,
        "quantityDefault": 1,
        "itemDiscPercent": "",
        "dataClassification8Id": null,
        "salesQuotationId": null,
        "salesman5Id": null,
        "deliveryOrderId": 245204,
        "dataClassification3Id": null,
        "salesman1Id": 150,
        "tax3Id": null,
        "controlQuantity": 0,
        "grossAmount": 180630.630631,
        "projectId": null,
        "dppAmount": 180630.630631,
        "tax2Amount": 0,
        "dynamicGroup": false,
        "posSalesTypeId": null,
        "dataClassification10Id": null,
        "itemCashDiscount": 0,
        "dataClassification9Id": null,
        "salesmanList": [
          {
            "resignMonth": null,
            "departmentId": null,
            "optLock": 1,
            "joinDateView": "27 Dec 2019",
            "resignYear": null,
            "contactInfoId": 150,
            "bankName": null,
            "startMonthPayment": 12,
            "nikNo": null,
            "addressId": 200,
            "number": "E.00003",
            "joinDate": "27/12/2019",
            "salesmanUserId": null,
            "nettoIncomeBefore": 0,
            "id": 150,
            "pphBefore": 0,
            "posRoleId": null,
            "startYearPayment": 2019,
            "employeeTaxStatus": "TK0",
            "bankAccount": null,
            "bankAccountName": null,
            "domisiliType": "INA",
            "branchId": 50,
            "bankCode": null,
            "calculatePtkp": true,
            "pph": true,
            "npwpNo": null,
            "suspended": false,
            "employeeWorkStatus": "PEGAWAI_TETAP",
            "name": "DIST-YUFA",
            "salesman": true,
            "resign": false
          }
        ],
        "department": {
          "sub": true,
          "parent": {
            "sub": true,
            "parent": {
              "sub": false,
              "parent": {
                "sub": false,
                "parent": null,
                "lvl": 0,
                "nameWithIndentStrip": "Root",
                "optLock": 0,
                "name": "Root",
                "description": null,
                "parentNode": true,
                "nameWithIndent": "Root",
                "id": 50,
                "suspended": false
              },
              "lvl": 1,
              "nameWithIndentStrip": "DEPT. SPAREPART",
              "optLock": 0,
              "name": "DEPT. SPAREPART",
              "description": null,
              "parentNode": true,
              "nameWithIndent": "DEPT. SPAREPART",
              "id": 51,
              "suspended": false
            },
            "lvl": 2,
            "nameWithIndentStrip": "- DISTRIBUTOR.",
            "optLock": 0,
            "name": "DISTRIBUTOR.",
            "description": null,
            "parentNode": true,
            "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR.",
            "id": 53,
            "suspended": false
          },
          "lvl": 3,
          "nameWithIndentStrip": "- - DISTRIBUTOR",
          "optLock": 0,
          "name": "DISTRIBUTOR",
          "description": null,
          "parentNode": false,
          "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR",
          "id": 54,
          "suspended": false
        },
        "salesman4Id": null,
        "tax3": null,
        "detailTaxName": "PPN 11%",
        "dataClassification5Id": null,
        "dataClassification4Id": null,
        "quantity": 1,
        "detailDynamicGroup": false,
        "totalCaptionSerialNumber": "0 No Seri/Produksi. Isikan 1 lagi",
        "numericField9": 0,
        "numericField8": 0,
        "numericField7": 0,
        "numericField6": 0,
        "numericField5": 0,
        "deliveryOrderPoNumber": "",
        "numericField4": 0,
        "itemUnitId": 50,
        "numericField3": 0,
        "salesAmountBase": 180630.630631,
        "numericField2": 0,
        "itemHistoryId": null,
        "numericField1": 0,
        "unitRatio": 1
      },
      {
        "deliveryOrderDetailId": 541026,
        "hasPosSalesType": false,
        "lastItemDiscPercent": "",
        "charField8": null,
        "returnQuantity": 0,
        "detailDynamicGroupTotalPrice": 0,
        "charField9": null,
        "processQuantityDesc": "",
        "charField6": null,
        "tax1Rate": 11,
        "charField7": null,
        "numericField10": 0,
        "charField4": null,
        "departmentId": 54,
        "charField5": null,
        "optLock": 34,
        "itemUnit": {
          "optLock": 0,
          "name": "SET",
          "id": 100
        },
        "detailSerialNumber": [],
        "salesOrderPoNumber": "",
        "waitressEmployeeId": null,
        "deliveryOrderDetail": {
          "id": 541026
        },
        "charField2": null,
        "charField3": null,
        "salesOrderDetailId": 835013,
        "reverseInvoiceUnitCost": 0,
        "charField1": "MD075404-I",
        "id": 492672,
        "salesman3Id": null,
        "dataClassification6Id": null,
        "salesQuotationDetailId": null,
        "unitPrice": 208500,
        "useTax1": true,
        "dateField2": null,
        "dataClassification1": null,
        "salesmanName": "DIST-YUFA",
        "branchId": 50,
        "useTax3": false,
        "dataClassification3": null,
        "item": {
          "unit2Id": null,
          "charField8": null,
          "charField9": null,
          "charField6": null,
          "charField7": null,
          "numericField10": 0,
          "unit4Price": 0,
          "charField4": null,
          "charField5": null,
          "optLock": 21,
          "percentTaxable": 100,
          "itemBrandId": null,
          "ratioVendorUnit": 1,
          "unit3Price": 0,
          "salesDiscountGlAccountId": 211,
          "itemProduced": true,
          "charField2": null,
          "charField3": null,
          "charField1": "SLOW MOVING",
          "id": 1438,
          "maxOptionModifier": null,
          "unitPrice": 0,
          "dateField2": null,
          "branchId": null,
          "tax1Id": 50,
          "dateField1": null,
          "useWholesalePrice": false,
          "onSales": 0,
          "unit5Price": 0,
          "unit2Price": 0,
          "suspended": false,
          "goodTransitGlAccountId": 126,
          "cogsGlAccountId": 214,
          "referenceSubstitutionId": null,
          "shortName": "KAP NKEN AS ASSY MI. L038/ 4D5",
          "itemSubstitutionId": null,
          "charField10": null,
          "unBilledGlAccountId": 197,
          "canChangeDetailGroup": false,
          "variantLabel2": null,
          "unit3Id": null,
          "dimWidth": 0,
          "variantLabel1": null,
          "salesRetGlAccountId": 208,
          "dimDepth": 0,
          "minimumQuantityReorder": 2,
          "lockTime": null,
          "vendorPrice": 0,
          "minimumQuantity": 0,
          "tax4Id": null,
          "dimHeight": 0,
          "additionalCost": false,
          "unit4Id": null,
          "notes": "EP-KNA01-MD075404(I)",
          "purchaseRetGlAccountId": 123,
          "unit1": {
            "optLock": 0,
            "name": "SET",
            "id": 100
          },
          "variantParentId": null,
          "unit2": null,
          "unit3": null,
          "vendorUnit": {
            "optLock": 0,
            "name": "SET",
            "id": 100
          },
          "preferedVendorId": null,
          "ratio2": 0,
          "unit4": null,
          "unit5": null,
          "ratio4": 0,
          "ratio3": 0,
          "ratio5": 0,
          "variantDetail2": null,
          "tax3Id": null,
          "inventoryGlAccountId": 123,
          "variantDetail1": null,
          "controlQuantity": false,
          "weight": null,
          "upcNo": "MD075404-I",
          "substituted": false,
          "minOptionModifier": 1,
          "salesGlAccountId": 205,
          "name": "KAP NOKEN AS ASSY MI. L038/ 4D56 UTM",
          "deliveryLeadTime": 0,
          "manageExpired": false,
          "no": "EP-KNA01-MD075404-I",
          "itemType": "INVENTORY",
          "defaultDiscount": null,
          "unit1Id": 100,
          "unit5Id": null,
          "itemCategoryId": 103,
          "hasImage": false,
          "tax1": {
            "pphPs4Type": null,
            "purchaseTaxGlAccountId": 82,
            "rate": 11,
            "pph23Type": null,
            "optLock": 3,
            "salesTaxGlAccountId": 81,
            "description": "Pajak Pertambahan Nilai",
            "pph15Type": null,
            "id": 50,
            "taxCode": "PPN",
            "taxType": "PPN",
            "taxInfo": "PPN 11%"
          },
          "tax2": null,
          "manageSN": false,
          "materialProduced": true,
          "variantSeq": null,
          "tax3": null,
          "tax4": null,
          "serialNumberType": null,
          "tax2Id": null,
          "cost": 0,
          "printDetailGroup": false,
          "calculateGroupPrice": false,
          "numericField9": 0,
          "defStandardCost": 0,
          "numericField8": 0,
          "numericField7": 0,
          "numericField6": 0,
          "numericField5": 0,
          "numericField4": 0,
          "numericField3": null,
          "numericField2": null,
          "numericField1": null,
          "vendorUnitId": 100,
          "unit1Price": 0
        },
        "purchaseInvoiceDetailId": null,
        "dataClassification1Id": null,
        "useTax2": false,
        "dateField1": null,
        "dataClassification2": null,
        "dataClassification5": null,
        "dataClassification4": null,
        "dataClassification7": null,
        "dataClassification6": null,
        "dataClassification9": null,
        "dataClassification8": null,
        "posSalesType": null,
        "tax1Amount": 41324.324324,
        "detailNotes": null,
        "warehouse": {
          "defaultWarehouse": true,
          "scrapWarehouse": false,
          "locationId": 52,
          "optLock": 3,
          "name": "HJA 1",
          "description": null,
          "pic": null,
          "id": 50,
          "suspended": false
        },
        "salesOrder": {
          "number": "SO24-11-1054-D",
          "id": 252303
        },
        "itemId": 1438,
        "warehouseId": 50,
        "charField15": null,
        "charField13": null,
        "charField14": null,
        "charField11": null,
        "charField12": null,
        "useTax4": false,
        "charField10": null,
        "canChangeDetailGroup": false,
        "dataClassification10": null,
        "detailDynamicGroupPrice": 0,
        "detailName": "KAP NOKEN AS ASSY MI. L038/ 4D56 UTM",
        "lastItemCashDiscount": 0,
        "totalPrice": 417000,
        "salesInvoiceId": 202953,
        "groupSeq": null,
        "salesAmount": 375675.675676,
        "purchaseInvoiceId": null,
        "dataClassification7Id": null,
        "seq": 3,
        "dataClassification2Id": null,
        "salesman2Id": null,
        "searchCharField1": {
          "id": "MD075404-I",
          "name": "MD075404-I"
        },
        "deliveryOrder": {
          "number": "DO2024-30952HJA",
          "id": 245063
        },
        "salesOrderDetail": {
          "id": 835013
        },
        "salesOrderId": 252303,
        "project": null,
        "deliveredQuantity": 0,
        "quantityDefault": 2,
        "itemDiscPercent": "",
        "dataClassification8Id": null,
        "salesQuotationId": null,
        "salesman5Id": null,
        "deliveryOrderId": 245063,
        "dataClassification3Id": null,
        "salesman1Id": 150,
        "tax3Id": null,
        "controlQuantity": 0,
        "grossAmount": 375675.675676,
        "projectId": null,
        "dppAmount": 375675.675676,
        "tax2Amount": 0,
        "dynamicGroup": false,
        "posSalesTypeId": null,
        "dataClassification10Id": null,
        "itemCashDiscount": 0,
        "dataClassification9Id": null,
        "salesmanList": [
          {
            "resignMonth": null,
            "departmentId": null,
            "optLock": 1,
            "joinDateView": "27 Dec 2019",
            "resignYear": null,
            "contactInfoId": 150,
            "bankName": null,
            "startMonthPayment": 12,
            "nikNo": null,
            "addressId": 200,
            "number": "E.00003",
            "joinDate": "27/12/2019",
            "salesmanUserId": null,
            "nettoIncomeBefore": 0,
            "id": 150,
            "pphBefore": 0,
            "posRoleId": null,
            "startYearPayment": 2019,
            "employeeTaxStatus": "TK0",
            "bankAccount": null,
            "bankAccountName": null,
            "domisiliType": "INA",
            "branchId": 50,
            "bankCode": null,
            "calculatePtkp": true,
            "pph": true,
            "npwpNo": null,
            "suspended": false,
            "employeeWorkStatus": "PEGAWAI_TETAP",
            "name": "DIST-YUFA",
            "salesman": true,
            "resign": false
          }
        ],
        "department": {
          "sub": true,
          "parent": {
            "sub": true,
            "parent": {
              "sub": false,
              "parent": {
                "sub": false,
                "parent": null,
                "lvl": 0,
                "nameWithIndentStrip": "Root",
                "optLock": 0,
                "name": "Root",
                "description": null,
                "parentNode": true,
                "nameWithIndent": "Root",
                "id": 50,
                "suspended": false
              },
              "lvl": 1,
              "nameWithIndentStrip": "DEPT. SPAREPART",
              "optLock": 0,
              "name": "DEPT. SPAREPART",
              "description": null,
              "parentNode": true,
              "nameWithIndent": "DEPT. SPAREPART",
              "id": 51,
              "suspended": false
            },
            "lvl": 2,
            "nameWithIndentStrip": "- DISTRIBUTOR.",
            "optLock": 0,
            "name": "DISTRIBUTOR.",
            "description": null,
            "parentNode": true,
            "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR.",
            "id": 53,
            "suspended": false
          },
          "lvl": 3,
          "nameWithIndentStrip": "- - DISTRIBUTOR",
          "optLock": 0,
          "name": "DISTRIBUTOR",
          "description": null,
          "parentNode": false,
          "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR",
          "id": 54,
          "suspended": false
        },
        "salesman4Id": null,
        "tax3": null,
        "detailTaxName": "PPN 11%",
        "dataClassification5Id": null,
        "dataClassification4Id": null,
        "quantity": 2,
        "detailDynamicGroup": false,
        "totalCaptionSerialNumber": "0 No Seri/Produksi. Isikan 2 lagi",
        "numericField9": 0,
        "numericField8": 0,
        "numericField7": 0,
        "numericField6": 0,
        "numericField5": 0,
        "deliveryOrderPoNumber": "",
        "numericField4": 0,
        "itemUnitId": 100,
        "numericField3": 0,
        "salesAmountBase": 375675.675676,
        "numericField2": 0,
        "itemHistoryId": null,
        "numericField1": 0,
        "unitRatio": 1
      }
    ],
    "employeePayment": false,
    "expenseAccrual": false,
    "salesReturn": false,
    "referenceNumberTax": null,
    "status": "OUTSTANDING",
    "lastTaxPaymentDate": null,
    "bankTransfer": false,
    "deliveryOrderHistory": [],
    "jobOrder": false,
    "statusOutstanding": "Belum Lunas",
    "salesAmount": 3788744.106,
    "downPaymentUsed": 0,
    "masterPosSalesTypeId": null,
    "statusName": "Belum Lunas",
    "dpTax3Id": null,
    "primeOwing": 4205505.106,
    "tax2AmountBase": 0,
    "tax4Id": null,
    "tax4Rate": 0,
    "efakturFileName": null,
    "taxDate": "18/11/2024",
    "onlineOrderId": null,
    "approvalTypeNumberId": null,
    "canDelivery": false,
    "purchaseReturn": false,
    "totalExpense": 0,
    "documentCode": "DIGUNGGUNG",
    "stockOpnameResult": false,
    "exchangeInvoice": null,
    "subTotal": 4205505.106,
    "lastCashDiscount": 0,
    "manufactureOrder": false,
    "returnDownPayment": 0,
    "masterSalesmanName": "DIST-YUFA",
    "exchangeInvoiceDueDate": null,
    "tax2Rate": 0,
    "epaymentSetting": null,
    "finishedProject": false,
    "openingBalance": false,
    "fiscalRate": 1,
    "epaymentType": null,
    "orderDownPaymentId": null,
    "paymentWithUniqueAmount": false,
    "assetTransfer": false,
    "recurringDetailId": null,
    "tax4AmountBase": 0,
    "totalAmountWithUniqueAmount": 0,
    "stockOpnameOrder": false,
    "detailSchedulePayment": [],
    "exchangeInvoiceNumber": null,
    "approvalDetailList": [],
    "totalAmount": 4205505.106,
    "hourTime": 11,
    "shipDateView": "18 Nov 2024",
    "paymentTermIsInstallment": false,
    "manualApprovalNumber": null,
    "purchaseRequisition": false,
    "paymentTerm": {
      "cashOnDelivery": false,
      "optLock": 0,
      "discDays": 0,
      "installmentTerm": false,
      "name": "net 60",
      "defaultTerm": false,
      "memo": null,
      "discPC": 0,
      "id": 56,
      "netDays": 60,
      "suspended": false,
      "manualTerm": false
    },
    "noneInvoiceReturn": false,
    "dppAmount": 3788744.106,
    "finishedGoodSlip": false,
    "tax2Amount": 0,
    "purchasePayment": false,
    "snRequired": false,
    "otherDeposit": false,
    "otherPayment": false,
    "receiptHistory": [],
    "tax1": {
      "pphPs4Type": null,
      "purchaseTaxGlAccountId": 82,
      "rate": 11,
      "pph23Type": null,
      "optLock": 3,
      "salesTaxGlAccountId": 81,
      "description": "Pajak Pertambahan Nilai",
      "pph15Type": null,
      "id": 50,
      "taxCode": "PPN",
      "taxType": "PPN",
      "taxInfo": "PPN 11%"
    },
    "costDistribution": false,
    "tax2": null,
    "itemTransfer": false,
    "vendorClaim": false,
    "forceCalculateTaxRate": false,
    "reversePercentShippedPoint": "0%",
    "tax3Amount": 0,
    "materialEquipment": false,
    "tax4": null,
    "cashDiscPercent": "",
    "efakturEmailUserId": null,
    "hasDeliveryPacking": false,
    "multiTaxRate": false,
    "branchName": "Kantor Pusat",
    "materialAdjustment": false,
    "totalDownPayment": 0,
    "subComp": null,
    "fixedAsset": false,
    "epaymentStatusName": "Belum terbayar",
    "attachmentCount": 0,
    "standardProductCost": false,
    "arAccount": {
      "no": "11.20.10.02",
      "sub": true,
      "parent": {
        "no": "11.20.10.00",
        "sub": true,
        "parent": {
          "no": "11.20.00.00",
          "sub": false,
          "parent": {
            "no": null,
            "sub": false,
            "parent": null,
            "lvl": 0,
            "accountType": null,
            "optLock": 0,
            "memo": null,
            "accountTypeName": "",
            "parentNode": true,
            "nameWithIndent": "Root",
            "suspended": false,
            "autoNumberTransactionId": null,
            "nameWithIndentStrip": "Root",
            "fiscal": false,
            "noWithIndent": "null",
            "name": "Root",
            "id": 50,
            "currencyId": null
          },
          "lvl": 1,
          "accountType": "ACCOUNT_RECEIVABLE",
          "optLock": 0,
          "memo": null,
          "accountTypeName": "Piutang Usaha",
          "parentNode": true,
          "nameWithIndent": "PIUTANG DAGANG",
          "suspended": false,
          "autoNumberTransactionId": null,
          "nameWithIndentStrip": "PIUTANG DAGANG",
          "fiscal": false,
          "noWithIndent": "11.20.00.00",
          "name": "PIUTANG DAGANG",
          "id": 111,
          "currencyId": 50
        },
        "lvl": 2,
        "accountType": "ACCOUNT_RECEIVABLE",
        "optLock": 0,
        "memo": null,
        "accountTypeName": "Piutang Usaha",
        "parentNode": true,
        "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;Piutang Dagang",
        "suspended": false,
        "autoNumberTransactionId": null,
        "nameWithIndentStrip": "- Piutang Dagang",
        "fiscal": false,
        "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;11.20.10.00",
        "name": "Piutang Dagang",
        "id": 112,
        "currencyId": 50
      },
      "lvl": 3,
      "accountType": "ACCOUNT_RECEIVABLE",
      "optLock": 1,
      "memo": null,
      "accountTypeName": "Piutang Usaha",
      "parentNode": false,
      "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Piutang Dagang Sparepart Distributor",
      "suspended": false,
      "autoNumberTransactionId": null,
      "nameWithIndentStrip": "- - Piutang Dagang Sparepart Distributor",
      "fiscal": false,
      "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;11.20.10.02",
      "name": "Piutang Dagang Sparepart Distributor",
      "id": 115,
      "currencyId": 50
    },
    "customer": {
      "documentCode": "DIGUNGGUNG",
      "consignmentStore": false,
      "referenceCustomerLimitId": null,
      "charField8": null,
      "customerLimitAmountValue": 100000000,
      "charField9": null,
      "charField6": null,
      "contactInfo": {
        "mobilePhone": null,
        "homePhone": null,
        "workPhone": "81215958080",
        "email": null
      },
      "charField7": null,
      "numericField10": 0,
      "idCard": null,
      "charField4": null,
      "charField5": null,
      "optLock": 340,
      "lastBank": {
        "no": "11.10.20.01",
        "sub": true,
        "parent": {
          "no": "11.10.20.00",
          "sub": true,
          "parent": {
            "no": "11.10.00.00",
            "sub": false,
            "parent": {
              "no": null,
              "sub": false,
              "parent": null,
              "lvl": 0,
              "accountType": null,
              "optLock": 0,
              "memo": null,
              "accountTypeName": "",
              "parentNode": true,
              "nameWithIndent": "Root",
              "suspended": false,
              "autoNumberTransactionId": null,
              "nameWithIndentStrip": "Root",
              "fiscal": false,
              "noWithIndent": "null",
              "name": "Root",
              "id": 50,
              "currencyId": null
            },
            "lvl": 1,
            "accountType": "CASH_BANK",
            "optLock": 0,
            "memo": null,
            "accountTypeName": "Kas & Bank",
            "parentNode": true,
            "nameWithIndent": "KAS & SETARA KAS",
            "suspended": false,
            "autoNumberTransactionId": 100,
            "nameWithIndentStrip": "KAS & SETARA KAS",
            "fiscal": false,
            "noWithIndent": "11.10.00.00",
            "name": "KAS & SETARA KAS",
            "id": 100,
            "currencyId": 50
          },
          "lvl": 2,
          "accountType": "CASH_BANK",
          "optLock": 0,
          "memo": null,
          "accountTypeName": "Kas & Bank",
          "parentNode": true,
          "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;Bank (IDR)",
          "suspended": false,
          "autoNumberTransactionId": 103,
          "nameWithIndentStrip": "- Bank (IDR)",
          "fiscal": false,
          "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;11.10.20.00",
          "name": "Bank (IDR)",
          "id": 103,
          "currencyId": 50
        },
        "lvl": 3,
        "accountType": "CASH_BANK",
        "optLock": 0,
        "memo": null,
        "accountTypeName": "Kas & Bank",
        "parentNode": false,
        "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;BCA 046-1787770",
        "suspended": false,
        "autoNumberTransactionId": 104,
        "nameWithIndentStrip": "- - BCA 046-1787770",
        "fiscal": false,
        "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;11.10.20.01",
        "name": "BCA 046-1787770",
        "currency": {
          "symbol": "Rp",
          "defaultArAccountId": 57,
          "code": "IDR",
          "defaultSalesDiscAccountId": 60,
          "optLock": 7,
          "currencyConverterType": "TO_LOCAL",
          "defaultAdvSalesAccountId": 59,
          "defaultAdvPurchaseAccountId": 58,
          "defaultRealizeGlAccountId": 61,
          "name": "Indonesian Rupiah",
          "codeSymbol": "IDR Rp",
          "id": 50,
          "defaultApAccountId": 56,
          "defaultUnrealizeGlAccountId": 62
        },
        "id": 104,
        "currencyId": 50
      },
      "customerLimitAge": true,
      "defaultIncTax": true,
      "groupCustomerLimit": false,
      "charField2": null,
      "charField3": null,
      "charField1": null,
      "id": 62,
      "salesman3Id": null,
      "currencyId": 50,
      "arAccountCount": 1,
      "salesman5Id": null,
      "dateField2": null,
      "branchId": null,
      "shipSameAsBill": true,
      "dateField1": null,
      "defaultTermId": 56,
      "pkpNo": null,
      "npwpNo": null,
      "suspended": false,
      "warehouseId": null,
      "name": "AUTOPARTS MOTOR TOKO",
      "shipAddressList": [
        {
          "country": "",
          "branchId": null,
          "zipCode": "",
          "notes": "AUTOPARTS MOTOR TOKO",
          "address": "JL. RAYA TELUKAN 9A SOLO BACEM\nSOLO",
          "city": "SOLO",
          "latitude": null,
          "optLock": 2,
          "vendorId": null,
          "employeeId": null,
          "suspended": false,
          "taxLocation": true,
          "deleted": false,
          "province": "",
          "warehouseId": null,
          "street": "JL. RAYA TELUKAN 9A SOLO BACEM",
          "customerId": 62,
          "name": "AUTOPARTS MOTOR TOKO",
          "concatFullAddress": "JL. RAYA TELUKAN 9A SOLO BACEM SOLO",
          "id": 287,
          "projectId": null,
          "headQuarter": false,
          "longitude": null
        }
      ],
      "salesman": {
        "resignMonth": null,
        "departmentId": null,
        "optLock": 1,
        "joinDateView": "27 Dec 2019",
        "resignYear": null,
        "contactInfoId": 150,
        "bankName": null,
        "startMonthPayment": 12,
        "nikNo": null,
        "addressId": 200,
        "number": "E.00003",
        "joinDate": "27/12/2019",
        "salesmanUserId": null,
        "nettoIncomeBefore": 0,
        "id": 150,
        "pphBefore": 0,
        "posRoleId": null,
        "startYearPayment": 2019,
        "employeeTaxStatus": "TK0",
        "bankAccount": null,
        "bankAccountName": null,
        "domisiliType": "INA",
        "branchId": 50,
        "bankCode": null,
        "calculatePtkp": true,
        "pph": true,
        "npwpNo": null,
        "suspended": false,
        "employeeWorkStatus": "PEGAWAI_TETAP",
        "name": "DIST-YUFA",
        "salesman": true,
        "resign": false
      },
      "defaultInvoiceDesc": null,
      "charField10": null,
      "notesIdTax": null,
      "shipAddressId": 287,
      "wpName": "AUTOPARTS MOTOR TOKO",
      "customerTaxType": "BKN_PEMUNGUT_PPN",
      "salesman4Id": null,
      "taxSameAsBill": true,
      "customerLimitAgeValue": 100,
      "taxAddressId": 287,
      "salesman2Id": null,
      "priceCategoryId": 50,
      "defaultSalesmanId": 150,
      "defaultWarehouseId": null,
      "billAddressId": 287,
      "reseller": false,
      "customerNoVa": null,
      "shipAddress": {
        "country": "",
        "branchId": null,
        "zipCode": "",
        "notes": "AUTOPARTS MOTOR TOKO",
        "address": "JL. RAYA TELUKAN 9A SOLO BACEM\nSOLO",
        "city": "SOLO",
        "latitude": null,
        "optLock": 2,
        "vendorId": null,
        "employeeId": null,
        "suspended": false,
        "taxLocation": true,
        "deleted": false,
        "province": "",
        "warehouseId": null,
        "street": "JL. RAYA TELUKAN 9A SOLO BACEM",
        "customerId": 62,
        "name": "AUTOPARTS MOTOR TOKO",
        "concatFullAddress": "JL. RAYA TELUKAN 9A SOLO BACEM SOLO",
        "id": 287,
        "projectId": null,
        "headQuarter": false,
        "longitude": null
      },
      "numericField9": 0,
      "defaultSalesDisc": null,
      "numericField8": 0,
      "numericField7": 0,
      "numericField6": 0,
      "numericField5": 0,
      "numericField4": 0,
      "efakturSendEmail": null,
      "numericField3": null,
      "numericField2": null,
      "numericField1": null,
      "categoryId": 100,
      "discountCategoryId": 100,
      "customerNo": "SLT004D",
      "customerLimitAmount": true
    },
    "reverseInvoiceStatusName": "",
    "detailTax": [
      {
        "taxableAmount": 3788743.338739,
        "transId": 202953,
        "optLock": 34,
        "tax": {
          "pphPs4Type": null,
          "purchaseTaxGlAccountId": 82,
          "rate": 11,
          "pph23Type": null,
          "optLock": 3,
          "salesTaxGlAccountId": 81,
          "description": "Pajak Pertambahan Nilai",
          "pph15Type": null,
          "id": 50,
          "taxCode": "PPN",
          "taxType": "PPN",
          "taxInfo": "PPN 11%"
        },
        "_status": "BROWSE",
        "hasPaid": false,
        "taxRate": 11,
        "taxId": 50,
        "taxDescription": "Pajak Pertambahan Nilai",
        "id": 258715,
        "taxAmount": 416761,
        "currencyId": 50,
        "taxType": "PPN"
      }
    ]
  }
    "taxDateView": "18 Nov 2024",
    "reverseInvoice": false,
    "charField8": "",
    "charField9": "",
    "tax4Amount": 0,
    "charField6": "",
    "invoiceTime": "11:15:01",
    "charField7": "",
    "numericField10": 0,
    "charField4": "",
    "inclusiveTax": true,
    "dueDate": "17/01/2025",
    "charField5": "",
    "subTotal": 4205505.106,
    "branch": {
      "optLock": 1,
      "defaultBranch": true,
      "name": "Kantor Pusat",
      "id": 50,
      "suspended": false
    },
    "customerCategoryName": "DISTRIBUTOR",
    "lastUpdateView": "18 Nov 2024 13:02:44",
    "number": "2411-0900DA",
    "exchangeInvoiceDueDate": null,
    "totalPayment": 0,
    "masterSalesman": {
      "bankAccount": null,
      "bankAccountName": null,
      "number": "E.00003",
      "joinDate": "27/12/2019",
      "joinDateView": "27 Dec 2019",
      "name": "DIST-YUFA",
      "calculatePtkp": true,
      "bankName": null,
      "salesman": true,
      "id": 150,
      "branch": {
        "optLock": 1,
        "defaultBranch": true,
        "name": "Kantor Pusat",
        "id": 50,
        "suspended": false
      },
      "suspended": false
    },
    "taxOwing": 0,
    "charField2": "",
    "charField3": "",
    "dueDateView": "17 Jan 2025",
    "id": 202953,
    "charField1": "",
    "openingBalance": false,
    "documentCodeName": "Digunggung",
    "masterPosSalesType": null,
    "transDateView": "18 Nov 2024",
    "dateField2": null,
    "dateField1": null,
    "taxable": true,
    "paymentWithUniqueAmount": false,
    "taxNumber": null,
    "totalAmountWithUniqueAmount": 0,
    "invoiceTimeView": "01 Jan 1970",
    "shipDate": "18/11/2024",
    "tax1Amount": 416761,
    "hasExchangeInvoice": false,
    "uniqueAmount": 0,
    "totalAmount": 4205505.106,
    "hourTime": 11,
    "createdByUserName": "sprsales.hjg@gmail.com",
    "shipDateView": "18 Nov 2024",
    "primeReturn": 0,
    "orderDownPayment": null,
    "lastUpdate": "18/11/2024 13:02:44",
    "cashierEmployee": null,
    "poNumber": null,
    "paymentTerm": {
      "cashOnDelivery": false,
      "optLock": 0,
      "discDays": 0,
      "installmentTerm": false,
      "name": "net 60",
      "memo": null,
      "defaultTerm": false,
      "discPC": 0,
      "id": 56,
      "netDays": 60,
      "suspended": false,
      "manualTerm": false
    },
    "charField10": "",
    "noneInvoiceReturn": false,
    "dppAmount": 3788744.106,
    "tax2Amount": 0,
    "availableDownPayment": 0,
    "taxReturn": 0,
    "description": "VIA BARAKA (BAYAR TUJUAN)",
    "invoiceDp": false,
    "invoicePrintedTime": "18/11/2024, 13:02",
    "downPaymentUsed": 0,
    "transDate": "18/11/2024",
    "lastPaymentDate": null,
    "statusName": "Belum Lunas",
    "masterDepartment": {
      "sub": true,
      "parent": {
        "sub": true,
        "parent": {
          "sub": false,
          "parent": {
            "sub": false,
            "parent": null,
            "lvl": 0,
            "nameWithIndentStrip": "Root",
            "optLock": 0,
            "name": "Root",
            "description": null,
            "parentNode": true,
            "nameWithIndent": "Root",
            "id": 50,
            "suspended": false
          },
          "lvl": 1,
          "nameWithIndentStrip": "DEPT. SPAREPART",
          "optLock": 0,
          "name": "DEPT. SPAREPART",
          "description": null,
          "parentNode": true,
          "nameWithIndent": "DEPT. SPAREPART",
          "id": 51,
          "suspended": false
        },
        "lvl": 2,
        "nameWithIndentStrip": "- DISTRIBUTOR.",
        "optLock": 0,
        "name": "DISTRIBUTOR.",
        "description": null,
        "parentNode": true,
        "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR.",
        "id": 53,
        "suspended": false
      },
      "lvl": 3,
      "nameWithIndentStrip": "- - DISTRIBUTOR",
      "optLock": 0,
      "name": "DISTRIBUTOR",
      "description": null,
      "parentNode": false,
      "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;DISTRIBUTOR",
      "id": 54,
      "suspended": false
    },
    "currency": {
      "symbol": "Rp",
      "code": "IDR",
      "name": "Indonesian Rupiah",
      "id": 50
    },
    "cashDiscount": 0,
    "primeOwing": 4205505.106,
    "primeReceipt": 0,
    "tax3Amount": 0,
    "approvalStatus": "APPROVED",
    "cashDiscPercent": "",
    "taxDate": "18/11/2024",
    "efakturFileName": null,
    "printedByUser": "sprsales.hjg@gmail.com",
    "totalDownPayment": 0,
    "taxReceipt": 0,
    "numericField9": 0,
    "numericField8": 0,
    "deliveryPackingNumber": "",
    "numericField7": 0,
    "numericField6": 0,
    "numericField5": 0,
    "numericField4": 0,
    "numericField3": 0,
    "totalDiscount": 4622532.894,
    "numericField2": 0,
    "numericField1": 0,
    "arAccount": {
      "no": "11.20.10.02",
      "sub": true,
      "parent": {
        "no": "11.20.10.00",
        "sub": true,
        "parent": {
          "no": "11.20.00.00",
          "sub": false,
          "parent": {
            "no": null,
            "sub": false,
            "parent": null,
            "lvl": 0,
            "accountType": null,
            "optLock": 0,
            "memo": null,
            "accountTypeName": "",
            "parentNode": true,
            "nameWithIndent": "Root",
            "suspended": false,
            "autoNumberTransactionId": null,
            "nameWithIndentStrip": "Root",
            "fiscal": false,
            "noWithIndent": "null",
            "name": "Root",
            "id": 50,
            "currencyId": null
          },
          "lvl": 1,
          "accountType": "ACCOUNT_RECEIVABLE",
          "optLock": 0,
          "memo": null,
          "accountTypeName": "Piutang Usaha",
          "parentNode": true,
          "nameWithIndent": "PIUTANG DAGANG",
          "suspended": false,
          "autoNumberTransactionId": null,
          "nameWithIndentStrip": "PIUTANG DAGANG",
          "fiscal": false,
          "noWithIndent": "11.20.00.00",
          "name": "PIUTANG DAGANG",
          "id": 111,
          "currencyId": 50
        },
        "lvl": 2,
        "accountType": "ACCOUNT_RECEIVABLE",
        "optLock": 0,
        "memo": null,
        "accountTypeName": "Piutang Usaha",
        "parentNode": true,
        "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;Piutang Dagang",
        "suspended": false,
        "autoNumberTransactionId": null,
        "nameWithIndentStrip": "- Piutang Dagang",
        "fiscal": false,
        "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;11.20.10.00",
        "name": "Piutang Dagang",
        "id": 112,
        "currencyId": 50
      },
      "lvl": 3,
      "accountType": "ACCOUNT_RECEIVABLE",
      "optLock": 1,
      "memo": null,
      "accountTypeName": "Piutang Usaha",
      "parentNode": false,
      "nameWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Piutang Dagang Sparepart Distributor",
      "suspended": false,
      "autoNumberTransactionId": null,
      "nameWithIndentStrip": "- - Piutang Dagang Sparepart Distributor",
      "fiscal": false,
      "noWithIndent": "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;11.20.10.02",
      "name": "Piutang Dagang Sparepart Distributor",
      "id": 115,
      "currencyId": 50
    },
    "masterProject": null,
    "totalDiscountDetail": 4622532.894,
    "totalExpense": 0,
    "age": 1,
    "customer": {
      "name": "AUTOPARTS MOTOR TOKO",
      "id": 62,
      "customerNo": "SLT004D"
    }
  }

